language: objective-c
before_install:
- brew install xctool
- export LANG=en_US.UTF-8
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- gem install cocoapods
- cd Example
- pod install
script:
- xctool test -workspace VOXHistogramView.xcworkspace -scheme VOXHistogramView-Example -sdk iphonesimulator
  ONLY_ACTIVE_ARCH=NO
notifications:
  email:
    recipients:
    - hawk.ukr@gmail.com
    on_success: change
    on_failure: always
